location: new orleans
optimize: set_kpcoef
epsilon: -1

service: supermarket

# add or restore
objective: add  #restore # 

# --- if add ---
candidate: bg_centroid
# how many destinations should be opened
#num_to_open: 4

plot: True


